X-Disk/config/routes.rb
Rails.application.routes.draw do
  
  resources :uploads, only: %i[create destroy]
  #login routes
  root 'sessions#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  #register routes
  get '/register' => 'users#new'
  post '/users' => 'users#create'

  get '/storage' => 'storage#index'
end

X-Disk/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

X-Disk/app/models/upload.rb
class Upload < ApplicationRecord
  before_destroy :delete_fil

  belongs_to :user
  mount_uploader :file, Uploader
  validates :file, presence: true
  

  def decode_file_name
    File.basename(CGI::unescape(self.file.to_s)).gsub(/%.*/, '')
  end


  #removing after destroy file from database
  def delete_fil
    self.file.remove!
  end
end

X-Disk/app/models/user.rb
class User < ApplicationRecord
  # Логин не должен превышать 15 символов
  validates :login, uniqueness: true, length: { maximum: 15 }
  # Пароль должен содержать буквы, цифры и спецсимволы,
  # быть не менее 8 и не более 30 символов в длину
  PASSWORD_FORMAT = /\A
    (?=.*\d)           # должна быть хотя бы одна цифра
    (?=.*[a-z])        # должна быть хотя бы одна строчная буква
    (?=.*[A-Z])        # должна быть хотя бы одна заглавная буква
    (?=.*[[:^alnum:]]) # должен быть хотя бы один спецсимвол
    .{8,30}            # должен быть не менее 8 и не более 30 символов в длину
  \z/x

  has_secure_password
  validates :password, presence: true, length: { minimum: 8, maximum: 30 }, format: { with: PASSWORD_FORMAT }
  validates :password_confirmation, presence: true
  
  # Пароль должен совпадать в полях "пароль" и "пароль повторно" при отправке формы
  validates_confirmation_of :password

  has_many :uploads, dependent: :destroy

  # Проверка доступного места для пользователя
  def available_space
    10.megabytes - self.uploads.sum { |upload| upload.file.size }

  end
end

X-Disk/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :is_auth?

  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def is_auth?
    redirect_to storage_path, notice: 'Вы уже вошли в систему.' if  current_user.present?
  end
end

X-Disk/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :is_auth?, only: [:create]

  def create
    user = User.find_by(login: params[:login])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to storage_path, notice: 'Вы успешно вошли в систему.'
    else
      flash[:alert] = 'Неверные логин или пароль.'
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Вы успешно вышли из системы.'
  end
end

X-Disk/app/controllers/storage_controller.rb
class StorageController < ApplicationController
 def index
  @upload = Upload.new
  @uploads = Upload.where(user_id: current_user.id).order(created_at: :desc)
 end
end

X-Disk/app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def create
    @upload = current_user.uploads.new(upload_params)
    if @upload.save
      redirect_to storage_path, notice: 'Файл успешно загружен.'
    else
      redirect_to storage_path, alert: @upload.errors.full_messages.join(', ')
    end
  end
  
  def destroy
    Upload.find(params[:id]).destroy
    redirect_to storage_path
  end

  private
  def upload_params
    params.require(:upload).permit(:file)
  end
 end
 

X-Disk/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_auth?, only: [:create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to storage_path, notice: 'Вы успешно зарегестрировались.'
    else
      if @user.errors.any?
        flash.now[:error] = @user.errors.full_messages.join(", ")
      end
      render :new, status: :unprocessable_entity
    end
  end
  

  private

  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end
end

X-Disk/app/helpers/application_helper.rb
module ApplicationHelper
end

X-Disk/app/helpers/sessions_helper.rb
module SessionsHelper
end

X-Disk/app/helpers/user_helper.rb
module UserHelper
end

X-Disk/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <% if current_user.present? %>
    <div class="navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item mr-3">
          <%= "#{current_user.login}" %>
        </li>
        &nbsp;
        <li class="nav-item mr-3" id="available-space" data-space="<%= current_user.available_space %>">
          <%= "Доступно #{number_to_human_size(current_user.available_space)}" %>
        </li>
        &nbsp;
        <li class="nav-item">
          <%= form_for @upload, url: uploads_path, html: { multipart: true } do |f| %>
            <% if flash[:alert].present? %>
              <div class="alert alert-danger">
                <%= flash[:alert] %>
              </div>
            <% end %>
            
            <div class="field">
              <%= f.file_field :file, id: "upload-file"  %>
            </div>

            <div class="actions">
              <%= f.submit "Загрузить" %>
            </div>
          <% end %>
        </li>
        <% if flash[:error].present? %>
          <li class="nav-item text-danger">
            <%= flash[:error] %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Выход", logout_path, method: :delete, class: 'nav-link font-weight-bold' %>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Вход", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Регистрация", register_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>

X-Disk/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>X-Disk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <% if flash[:notice].present? %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

X-Disk/app/views/users/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Регистрация</div>
        <div class="card-body">
          <%= form_with(model: @user, url: @users_path, local: true) do |form| %>
            <% if @user.errors.any? %>
              <div class="alert alert-danger">
                <h4>Форма содержит <%= pluralize(@user.errors.count, "ошибок") %>:</h4>
                <ul>
                  <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
              <%= form.label :login %>
              <%= form.text_field :login, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :password %>
              <%= form.password_field :password, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= form.label :password_confirmation %>
              <%= form.password_field :password_confirmation, class: 'form-control' %>
            </div>
            <br>
            <div class="actions">
              <%= form.submit 'Зарегистрироваться', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>